export const TEAM = [
  {
    src: "/team/img2.jpg",
    bg: "#6BBF7A",
    panel: "#F79B7F",
    name: "Ahmed Hassan",
    role: "Senior Frontend Developer",
    desc: "Crafts pixel-perfect UI components with React & Tailwind. Leads the design system at Homi, ensuring every interaction feels intuitive and smooth.",
    linkedin: "https://linkedin.com/in/ahmed-hassan",
    email: "ahmed@homi.dev",
    github: "https://github.com/ahmed-hassan",
  },
  {
    src: "/team/img3.jpg",
    bg: "#6bbcbf",
    panel: "#85CC92",
    name: "Sara Mohamed",
    role: "Frontend Architect",
    desc: "Builds scalable component libraries and optimizes performance. Passionate about accessibility and creating inclusive web experiences for all users.",
    linkedin: "https://linkedin.com/in/sara-mohamed",
    email: "sara@homi.dev",
    github: "https://github.com/sara-mohamed",
  },
  {
    src: "/team/img4.jpeg",
    bg: "#82e8c1",
    panel: "#ED9DC4",
    name: "Omar Khaled",
    role: "UI/UX Frontend Developer",
    desc: "Bridges design and code with Figma-to-React workflows. Specializes in animations, micro-interactions, and bringing architectural visions to life.",
    linkedin: "https://linkedin.com/in/omar-khaled",
    email: "omar@homi.dev",
    github: "https://github.com/omar-khaled",
  },
  {
    src: "/team/img5.jpg",
    bg: "#318ba1",
    panel: "#8DC4FF",
    name: "Laila Ibrahim",
    role: "Full Stack Frontend Lead",
    desc: "Manages state complexity and API integrations. Builds real-time features for Homi's architecture platform with React Query and WebSockets.",
    linkedin: "https://linkedin.com/in/laila-ibrahim",
    email: "laila@homi.dev",
    github: "https://github.com/laila-ibrahim",
  },
  {
    src: "/team/img1.jpg",
    bg: "#54b2c8",
    panel: "#DEB887",
    name: "Youssef Ali",
    role: "Junior Frontend Developer",
    desc: "Rapidly learning modern frontend stack. Contributes to component testing, Storybook documentation, and cross-browser compatibility at Homi.",
    linkedin: "https://linkedin.com/in/youssef-ali",
    email: "youssef@homi.dev",
    github: "https://github.com/youssef-ali",
  },
];
