export const TEAM = [
  {
    src: "/team/img-1.jpg",
    bg: "#0B0F14",
    name: "Mohamed Hamed",
    role: "FULL-STACK DEVELOPER",
    desc: "Builds scalable web applications with React, Node.js, and Supabase. Passionate about crafting modern interfaces and delivering seamless user experiences.",
    linkedin: "https://www.linkedin.com/in/mohamed-hamed-alkafory/",
    email: "alkmohamed40@gmail.com",
    github: "https://github.com/Mohamed-Alkafory",
  },
  {
    src: "/team/img-2.jpg",
    bg: "#F8FAFC",
    name: "Esraa Shalaby",
    role: "Frontend Developer",
    desc: "Passionate about creating clean, responsive, and user-friendly interfaces. Focused on delivering seamless user experiences through modern frontend technologies.",
    linkedin: "https://linkedin.com/in/sara-mohamed",
    email: "sara@homi.dev",
    github: "https://github.com/sara-mohamed",
  },
  {
    src: "/team/img-3.jpg",
    bg: "#82e8c1",
    name: "	Haneen Waleed",
    role: "Frontend Developer",
    desc: "Dedicated to building intuitive and visually engaging web applications with attention to performance, accessibility, and responsive design.",
    linkedin: "www.linkedin.com/in/haneen-waleed-abedlwahed",
    email: "hnyntym9@gmail.com",
    github: "https://github.com/HaneenWaleed",
  },
  {
    src: "/team/img-4.jpg",
    bg: "#318ba1",
    name: "Huda Elmorsi",
    role: "Frontend Developer",
    desc: "Frontend developer passionate about transforming ideas into elegant digital experiences using modern UI practices and clean, maintainable code.",
    linkedin: "https://linkedin.com/in/laila-ibrahim",
    email: "laila@homi.dev",
    github: "https://github.com/laila-ibrahim",
  },
  {
    src: "/team/img-5.jpeg",
    bg: "#82e8c1",
    name: "Shehab Hany",
    role: "Frontend Developer",
    desc: "Rapidly learning modern frontend stack. Contributes to component testing, Storybook documentation, and cross-browser compatibility at Homi.",
    linkedin: "https://www.linkedin.com/in/shehab-hany",
    email: "shehabhany4@outlook.com",
    github: "https://github.com/shehabhany4",
  },
];
